version: "3.8"

services:
  whaticket_backend:
    image: whaticket-backend:latest
    networks:
      - minha_rede    
    volumes:      
      - whaticket_backend_data:/usr/src/app/
    environment:
      # POSTGRES
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=0bdhs1bwdcj0ahlmdfjw1y5bn
      - DB_NAME=whaticket
      - TZ=America/Sao_Paulo

      # BACKEND
      - JWT_SECRET=G9qR8hKzP2wV5xN3m7bT4vC6xL9n2mB8
      - JWT_REFRESH_SECRET=X7pL4n9m2vB8c6xL9n2mB8G9qR8hKzP2
      - PORT=3000
      - PROXY_PORT=443
      - BACKEND_URL=https://homologapi.whatsflux.com.br
      - FRONTEND_URL=https://appv2.whatsflux.com.br
      - CHROME_ARGS=--no-sandbox --disable-setuid-sandbox

      # REDIS
      - REDIS_URI=redis://:0bdhs1bwdcj0ahlmdfjw1y5bn@redis:6379
      - REDIS_OPT_LIMITER_MAX=1
      - REDIS_OPT_LIMITER_DURATION=3000

      # GERENCIANET (PREENCHA SE NECESSÁRIO - Dados não encontrados no .env)
      - GERENCIANET_SANDBOX=false
      - GERENCIANET_CLIENT_ID=
      - GERENCIANET_CLIENT_SECRET=
      - GERENCIANET_PIX_CERT=
      - GERENCIANET_PIX_KEY=

      # USER LIMIT
      - USER_LIMIT=1000
      - CONNECTIONS_LIMIT=1000
      - CLOSED_SEND_BY_ME=true

      # MAIL (PREENCHA AGORA - No .env estavam como placeholders)
      - MAIL_HOST=smtp.hostinger.com
      - MAIL_USER=contato@seusite.com
      - MAIL_PASS=senha
      - MAIL_FROM=Recuperar Senha <contato@seusite.com>
      - MAIL_PORT=465
      - MAIL_SECURE=false
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 4096M    
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whaticket_backend.rule=Host(`homologapi.whatsflux.com.br`)"
        - "traefik.http.routers.whaticket_backend.entrypoints=websecure"
        - "traefik.http.routers.whaticket_backend.tls.certresolver=letsencryptresolver"
        - "traefik.http.middlewares.backend_headers.headers.customResponseHeaders.X-Frame-Options=SAMEORIGIN"
        - "traefik.http.middlewares.backend_headers.headers.customResponseHeaders.X-Content-Type-Options=nosniff"
        - "traefik.http.middlewares.backend_headers.headers.customResponseHeaders.X-XSS-Protection=1; mode=block"
        - "traefik.http.middlewares.backend_headers.headers.customResponseHeaders.Strict-Transport-Security=max-age=31536000; includeSubdomains;"
        - "traefik.http.middlewares.backend_headers.headers.customResponseHeaders.Referrer-Policy=no-referrer-when-downgrade"
        - "traefik.http.middlewares.backend_headers.headers.customResponseHeaders.Cache-Control=no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
        - "traefik.http.middlewares.backend_compress.compress=true"
        - "traefik.http.middlewares.backend_body_size.buffering.maxRequestBodyBytes=83886080"
        - "traefik.http.services.whaticket_backend.loadbalancer.server.port=3000"
        - "traefik.http.routers.whaticket_backend.service=whaticket_backend"
        - "traefik.http.routers.whaticket_backend.middlewares=backend_headers,backend_compress,backend_body_size"    
    

  whaticket_frontend:
    image: whaticket-frontend:latest
    networks:
      - minha_rede
    depends_on:
      - whaticket_backend
    volumes:      
      - whaticket_frontend_data:/usr/src/app/
    environment:
      - BACKEND_URL=https://homologapi.whatsflux.com.br
      - REACT_APP_BACKEND_URL=https://homologapi.whatsflux.com.br
      - REACT_APP_HOURS_CLOSE_TICKETS_AUTO=24
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 4096M    
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whaticket_frontend.rule=Host(`appv2.whatsflux.com.br`)"
        - "traefik.http.routers.whaticket_frontend.entrypoints=websecure"
        - "traefik.http.routers.whaticket_frontend.tls.certresolver=letsencryptresolver"
        - "traefik.http.middlewares.frontend_headers.headers.customResponseHeaders.X-Frame-Options=SAMEORIGIN"
        - "traefik.http.middlewares.frontend_headers.headers.customResponseHeaders.X-Content-Type-Options=nosniff"
        - "traefik.http.middlewares.frontend_headers.headers.customResponseHeaders.X-XSS-Protection=1; mode=block"
        - "traefik.http.middlewares.frontend_headers.headers.customResponseHeaders.Strict-Transport-Security=max-age=31536000; includeSubdomains;"
        - "traefik.http.middlewares.frontend_headers.headers.customResponseHeaders.Referrer-Policy=no-referrer-when-downgrade"
        - "traefik.http.middlewares.frontend_headers.headers.customResponseHeaders.Cache-Control=no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
        - "traefik.http.middlewares.frontend_compress.compress=true"
        - "traefik.http.middlewares.frontend_body_size.buffering.maxRequestBodyBytes=83886080"
        - "traefik.http.services.whaticket_frontend.loadbalancer.server.port=3250"
        - "traefik.http.routers.whaticket_frontend.service=whaticket_frontend"
        - "traefik.http.routers.whaticket_frontend.middlewares=frontend_headers,frontend_compress,frontend_body_size"
    
networks:
  minha_rede:
    driver: overlay
    attachable: true

volumes:
  whaticket_backend_data:
  whaticket_frontend_data:
