services:
  redis:
    image: redis:latest
    command: [
        "redis-server",
        "--appendonly",
        "yes",
        "--port",
        "6379",
        "--requirepass",
        "0bdhs1bwdcj0ahlmdfjw1y5bn"
      ]
    volumes:
      - redis_data:/data
    networks:
      - minha_rede
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M

volumes:
  redis_data:
    external: true
    name: redis_data

networks:
  minha_rede:
    external: true
    name: minha_rede
