version: "3.8"

# STACK WHATSFLUX - PRODUÇÃO (TRAEFIK)
# Esta é a sua stack oficial de deploy no Portainer.

services:
  whaticket_backend:
    image: whaticket-backend:latest
    networks:
      - minha_rede
    volumes:
      - whaticket_backend_data:/usr/src/app/
    environment:
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=0bdhs1bwdcj0ahlmdfjw1y5bn
      - DB_NAME=whaticket
      - TZ=America/Sao_Paulo
      - JWT_SECRET=G9qR8hKzP2wV5xN3m7bT4vC6xL9n2mB8
      - JWT_REFRESH_SECRET=X7pL4n9m2vB8c6xL9n2mB8G9qR8hKzP2
      - PORT=3000
      - PROXY_PORT=443
      - BACKEND_URL=https://homologapi.whatsflux.com.br
      - FRONTEND_URL=https://appv2.whatisflux.com.br
      - CHROME_ARGS=--no-sandbox --disable-setuid-sandbox
      - REDIS_URI=redis://:0bdhs1bwdcj0ahlmdfjw1y5bn@redis:6379
      - REDIS_OPT_LIMITER_MAX=1
      - REDIS_OPT_LIMITER_DURATION=3000
      - USER_LIMIT=1000
      - CONNECTIONS_LIMIT=1000
      - CLOSED_SEND_BY_ME=true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whaticket_backend.rule=Host(`homologapi.whatsflux.com.br`)"
        - "traefik.http.routers.whaticket_backend.entrypoints=websecure"
        - "traefik.http.routers.whaticket_backend.tls.certresolver=letsencryptresolver"
        - "traefik.http.middlewares.cors_backend.headers.accessControlAllowOriginList=https://appv2.whatisflux.com.br"
        - "traefik.http.middlewares.cors_backend.headers.accessControlAllowMethods=GET,HEAD,PUT,PATCH,POST,DELETE"
        - "traefik.http.middlewares.cors_backend.headers.accessControlAllowHeaders=Origin, X-Requested-With, Content-Type, Accept, Authorization"
        - "traefik.http.middlewares.cors_backend.headers.accessControlAllowCredentials=true"
        - "traefik.http.services.whaticket_backend.loadbalancer.server.port=3000"

  whaticket_frontend:
    image: whaticket-frontend:latest
    networks:
      - minha_rede
    depends_on:
      - whaticket_backend
    volumes:
      - whaticket_frontend_data:/usr/src/app/
    environment:
      - BACKEND_URL=https://homologapi.whatsflux.com.br
      - REACT_APP_BACKEND_URL=https://homologapi.whatsflux.com.br
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whaticket_frontend.rule=Host(`appv2.whatisflux.com.br`)"
        - "traefik.http.routers.whaticket_frontend.entrypoints=websecure"
        - "traefik.http.routers.whaticket_frontend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.whaticket_frontend.loadbalancer.server.port=3250"

networks:
  minha_rede:
    external: true
    name: minha_rede

volumes:
  whaticket_backend_data:
  whaticket_frontend_data:
